### ISSUE TITLE
RSA Cryptography Report TODO

### ISSUE THREAD

**Issue by akrooner** [akrooner/SENG440#2]
- [ ] Front page with title, author, affiliation and contact information (UVic, Dept.
of CS/ECE, student number, e-mail) and a blank dotted area to be filled in with
the submission date at the time of submission

- [ ] Introduction including a short description of the domain, performance
requirements, enumeration of the contributions, and project organization.

- [ ] Theoretical background

- [ ] One or more sections regarding the design process itself

- [ ] Performance/cost evaluation

- [ ] . Conclusions

- [ ] Bibliography

**Comment by akrooner** [comment]
**GRADING GUIDELINE**

- [ ] Functionally-correct C code (5 points)

- [ ] Optimized C code (10 points)

- [ ] Optimized assembly code (10 points)

- [ ] Firmware (5 points)

- [ ] Hardware (VHDL behavioral, timing estimation) (5 points)

- [ ] Hardware (automaton design, SpecCharts) (5 points)

- [ ] UML Description (5 points)

- [ ] Final Report (15 points)

**Comment by akrooner** [comment]
Completed
